### ISSUE TITLE
Add the option to run lint and unit test locally.

### ISSUE THREAD

**Issue by ignacio-chiazzo** [ignacio-chiazzo/Algorithms-Leetcode-Javascript#65]
The current repository uses a Github Action for running linters [Github workflows](https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript/blob/master/.github/workflows)

Add the option to run the linter locally by running commands. Optionally we can combine unit tests and lint and run them all in one command. There are also a few tests failing that should be updated.

**Comment by hot9cups** [comment]
As a first step, all the existing lint errors have been fixed, and the failing tests have been updated.
These changes can be found in the following PR - https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript/pull/67

**Comment by hot9cups** [comment]
I see that 
1. #67 fixed the failing tests and linting errors. 
2. #76 has the unit tests enhanced, `node Tests.js` enables running unit tests locally.
3. #70 enables running linter and automatic fixing locally via `eslint --fix`.

Once #76 is merged, I think we should be good to close this issue?

**Comment by ignacio-chiazzo** [comment]
Thanks for the amazing work on this @hot9cups!
