### ISSUE TITLE
Modifying Tests.js to handle multiple test exports

### ISSUE THREAD

**Issue by hot9cups** [ignacio-chiazzo/Algorithms-Leetcode-Javascript#68]
This is in response to the [comment](https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript/pull/67#discussion_r990804569) from my last PR.
I've been experimenting ever since, and I think there's a way it could be achieved.

What we want to do:
1. For every problem, if we have multiple solutions, then we would like to have multiple test functions, one for each solution. This should help in debugging as well as is a cleaner and more maintainable way of writing code. We should also be free to name our test functions anything, as opposed to the rigid and undescriptive names(`test` or in some cases `test1`,  `test2`, etc) we have right now, 
2. We want to modify Tests.js to be able to handle the test imports dynamically. Right now we hardcode it to invoke the `test` function as can be seen [here](https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript/blob/master/Test.js#L16). We want to get rid of this hardcoding as well as be able to invoke varying number of tests per test file as opposed to being able to invoke just 1 test per test file currently.

After having explored some of the options Javascript offers, I have found a solution to do this. 
I'll be happy to work on the PR if you'd like to assign the issue to me.

**Comment by ignacio-chiazzo** [comment]
>After having explored some of the options Javascript offers, I have found a solution to do this.

Could you elaborate on the solution you propose?


I'm totally cool with doing 

```problem_example.js
function testSolution1() { }

**Comment by hot9cups** [comment]
I'm on phone but I'll try to be elaborate.

So what you typed is kinda what we have already anyway, maybe with 1 degree of abstraction lesser where the code for both testSolution1 and testSolution2 for example is within the test method instead of being in separate functions, but either way this already exists. The problem is having to hardcode the method name to be test for instance instead of something more generic.

Again since this already exists, I thought your comment earlier was to help move to a state where we're allowed to have multiple functions with whatever named we'd like, have them all exported and run through the Tests.js file without having to hardcode the function names in Tests.js
If this isn't what you intended to begin with, well then this issue could be closed right away I guess.

Otherwise, the solution I have in mind is exporting all of the test methods in the test file.
Then having these imported in the Tests.js file as an Object, and looping through the functions in this Object and calling them. This enables us to 'just call the function' without having to know any of their names. This should also help make debugging slightly easier as we'd get the exact method that failed right at the first layer of the stack trace.

**Comment by ignacio-chiazzo** [comment]
oh I see what you mean. Yeah, running all the functions in the test file would be fantastic. We can use existing frameworks for that.

**Comment by ignacio-chiazzo** [comment]
Yes, that works for me

**Comment by hot9cups** [comment]
@ignacio-chiazzo Do you think we can close this issue now as we were able to achieve what we wanted?

Or do you have anything else in your mind that we could do to improve the test functionality?
