### ISSUE TITLE
Create and Add Easy, Medium and Hard level questions inside their respective folders

### ISSUE THREAD

**Issue by amritregmi26** [ignacio-chiazzo/Algorithms-Leetcode-Javascript#91]
Doing so will help contributors to find unsolved problems easily

**Comment by ignacio-chiazzo** [comment]
I like it!

**Comment by ignacio-chiazzo** [comment]
Thanks @amritregmi26, done by #92 

<img width="823" alt="Screenshot 2023-10-29 at 10 16 00 PM" src="https://github.com/ignacio-chiazzo/Algorithms-Leetcode-Javascript/assets/11672878/14341c70-4924-4bd0-9b9a-a840ffdfb663">

**Comment by amritregmi26** [comment]
Thanks brother !!! Now I'll contribute to this.
